# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/final_project/digital-design-project/music/music-1/music-1.cache/wt [current_project]
set_property parent.project_path D:/final_project/digital-design-project/music/music-1/music-1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property include_dirs D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new [current_fileset]
read_verilog -library xil_defaultlib {
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/debounce_circuit.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/one_pulse.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/pb_click.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/parallel_to_serial.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/pb_long_reset.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/global.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/freqdiv.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/freqdiv27.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/clock_generator_pb.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/buzzer_control.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/speaker_control.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/notes.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/ring_note.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/scan_ctl.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/display.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/inputs.v
  D:/final_project/digital-design-project/music/music-1/music-1.srcs/sources_1/new/speaker.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/final_project/digital-design-project/music/music-1/music-1.srcs/constrs_1/stopwatch.xdc
set_property used_in_implementation false [get_files D:/final_project/digital-design-project/music/music-1/music-1.srcs/constrs_1/stopwatch.xdc]


synth_design -top speaker -part xc7a35tcpg236-1


write_checkpoint -force -noxdef speaker.dcp

catch { report_utilization -file speaker_utilization_synth.rpt -pb speaker_utilization_synth.pb }
